### ISSUE TITLE
20w07a and 20w11a?

### ISSUE THREAD

**Issue by OwzygZawg** [InventivetalentDev/minecraft-assets#10]
Where is snapshot 20w07a and 20w11a? I need It. If possible!

**Comment by SchoolTARMaster** [comment]
Extract it yourself by downloading the game and extract from the .jar file.

**Comment by Felix14-v2** [comment]
> Extract it yourself by downloading the game and extract from the .jar file.

.jar contains not all resources.

**Comment by InventivetalentDev** [comment]
I'm only slightly late to this, but both versions have been added.
