### ISSUE TITLE
Add the .jar files (AKA the code)

### ISSUE THREAD

**Issue by cfrikke** [InventivetalentDev/minecraft-assets#16]
Add the code into the assets as that's technically an asset to minecraft

**Comment by barraIhsan** [comment]
I'm pretty sure it will violate [the terms of rule](https://www.minecraft.net/terms)

**Comment by cfrikke** [comment]
oh. Okay. That's fair enough. Wait, but this doesn't violate the terms of rule? Interesting.

**Comment by SchoolTARMaster** [comment]
The .jar file is basically the game. if you ask for it publicly, Mojang/Microsoft will sue InventivetalentDev.

**Comment by cfrikke** [comment]
Yes, I'm aware. That's what the other person said. I, uh, understand why
you can't do that.
