### ISSUE TITLE
License

### ISSUE THREAD

**Issue by monk-afk** [InventivetalentDev/minecraft-assets#17]
Is there a License associated with these assets?

**Comment by pron1mo** [comment]
Assets is a part of Mojang and Microsoft EULA, so short answer - yes.
Read [EULA ](https://www.minecraft.net/en-us/eula) and [Minecraft usage guideline](https://www.minecraft.net/en-us/usage-guidelines) for more information

**Comment by monk-afk** [comment]
aha perfect, that points me in the right direction. thank you!
