### ISSUE TITLE
Cannot clone this repository under Windows

### ISSUE THREAD

**Issue by vico93** [InventivetalentDev/minecraft-assets#2]
I tried to clone this repo using both Github for Windows and Git command line (Windows 10 x64) and in both cases i got errors in the middle of the cloning process, stating some files (eg.: `.github\FUNDING.yml`) are invalid.

**Comment by InventivetalentDev** [comment]
deleted those files, should work now :)

**Comment by tildejustin** [comment]
hey, any way you could fix this after the fact for at least releases 1.16-1.16.3?
