### ISSUE TITLE
Assets from 3D Shareware

### ISSUE THREAD

**Issue by barraIhsan** [InventivetalentDev/minecraft-assets#4]
So recently, I found a `3d.png`, and also `blue_key.png` in 1.16.4. But the problem there is no use for them, also it's not supposed to be there, they supposed to be in 3d shareware assets only

**Comment by barraIhsan** [comment]
Oh, also I found sounds.sys, it not supposed to be there

**Comment by InventivetalentDev** [comment]
it should properly delete any removed files in future asset versions now.

**Comment by barraIhsan** [comment]
ok, also why that happen anyway?

**Comment by InventivetalentDev** [comment]
because the master branch contained asset files for some reason and it wasn't removing those before adding the new ones

**Comment by barraIhsan** [comment]
oh ok
