### ISSUE TITLE
download issues and alternate site

### ISSUE THREAD

**Issue by RedMonster2** [InventivetalentDev/minecraft-assets#8]
there is an issue where i can't open GitHub zip files, so i was wondering if maybe you have something like an alternate site where you can post this that we can download from? thanks

**Comment by Errorcrafter** [comment]
you can right click the images from the previews on the repo itself and copy/download them.

**Comment by InventivetalentDev** [comment]
or go to a file on the website and click the "Download File" link, that'll take you directly to that file on github (or just right-click > save as)  
not sure why you can't open github zip files though  🤔

**Comment by SchoolTARMaster** [comment]
You can download the assets also from <a href="https://mcasset.cloud/">here</a>.
